version: '3.8'

networks:
  go-ios-iap-vendor:
    name: go-ios-iap-vendor

services:
  pg:
    image: mdillon/postgis
    container_name: go-ios-iap-vendor-postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - $DB_PORT:5432
    volumes:
      - ${DB_DATA_VOLUME}:/var/lib/postgresql/data
    networks:
      - go-ios-iap-vendor

